/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Dark Room/Dark_First.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useGLTFWithKTX2 } from '../../utility/useGLTFWithKTX2'
import { convertMaterialsToBasic } from '../../utility/convertToBasic'

export function DarkFirst(props) {
  const { nodes, materials } = useGLTFWithKTX2(
    "/models/Dark Room/Dark_First.glb"
  );

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mac_Screen.geometry} material={newMaterials.Mac_Screen} position={[-0.861, 0.815, 0.684]} rotation={[0, 0.523, 0]} />
      <mesh geometry={nodes.Computer_Screen.geometry} material={newMaterials['Computer scrreen']} position={[-0.302, 0.955, 0.647]} rotation={[0, -0.053, 0]} />
      <mesh geometry={nodes.First_Baked.geometry} material={newMaterials.first_real_realfdsa_Baked} position={[-0.231, -0.14, 0.652]} rotation={[Math.PI, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('')
