/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Dark Room/Dark_Targets.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useGLTFWithKTX2 } from '../../utility/useGLTFWithKTX2'
import { convertMaterialsToBasic } from '../../utility/convertToBasic'


export function DarkTargets(props) {
  const { nodes, materials } = useGLTFWithKTX2('/models/Dark Room/Dark_Targets.glb')

   const newMaterials = convertMaterialsToBasic(materials);
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.About_Hitbox.geometry} material={nodes.About_Hitbox.material} position={[0.679, 1.571, -1.368]} />
      <mesh geometry={nodes.About_Hitbox_Anim.geometry} material={nodes.About_Hitbox_Anim.material} position={[0.679, 1.571, -1.368]} />
      <mesh geometry={nodes.Dev_Work_Hitbox.geometry} material={nodes.Dev_Work_Hitbox.material} position={[-0.457, 0.597, 1.021]} />
      <mesh geometry={nodes.Dev_Work_Hitbox_Anim.geometry} material={nodes.Dev_Work_Hitbox_Anim.material} position={[-1.298, 1.166, 1.75]} />
    </group>
  )
}

useGLTF.preload('')
