/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Light Room/Light_Third.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useGLTFWithKTX2 } from '../../utility/useGLTFWithKTX2'
import { convertMaterialsToBasic } from '../../utility/convertToBasic'

export function LightThird(props) {
  const { nodes, materials } = useGLTFWithKTX2('/models/Light Room//Light_Third.glb');

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Light_Third_Baked.geometry} material={newMaterials.REAL_third_Baked} position={[24.79, -0.201, 0.173]} />
    </group>
  )
}

useGLTF.preload('')
