/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Light Room/Light_Second.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useGLTFWithKTX2 } from '../../utility/useGLTFWithKTX2'
import { convertMaterialsToBasic } from '../../utility/convertToBasic'

export function LightSecond(props) {
  const { nodes, materials } = useGLTFWithKTX2('/models/Light Room/Light_Second.glb');

  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Light_Second_Baked.geometry} material={newMaterials.actual_second_bro_Baked} position={[26.719, 1.498, 1.614]} rotation={[0, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('')
